name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: setup.py

    - run: pip install jupyterlab pytest nbval jupyter_packaging ipywidgets
    - run: pip install -ve .
    - run: jupyter labextension develop . --overwrite

    - name: Check labextension
      shell: bash -l {0}
      run: jupyter labextension list 2>&1 | grep -ie "@jupyter-widgets/jupyterlab-sidecar.*enabled.*ok" -

    - name: Run notebooks
      shell: bash -l {0}
      run: pytest .
